---
# tasks file for cvmfs-client

- name: Skip installation of cvmfs if /cvmfs path exists
  stat:
    path: /cvmfs
  register: p
  
- include_tasks: client_install.yml
  when: p.stat.isdir is not defined

- command: 'cvmfs_config stat -v {{ repository_name}}'
  register: cvmfs_stat
  ignore_errors: yes

- include_tasks: client_config.yml
  when: cvmfs_stat.rc != 0

- include_tasks: snapshotter_install.yml
  when: snapshotter|bool

- include_tasks: snapshotter_config.yml
  when: snapshotter|bool
