---
# defaults file for cvmfs-client

server_url: 'rgw.cloudveneto.it/cvmfswp6dc' 

repository_name: 'unpacked.infn.it'

cvmfs_server_url: 'https://{{ server_url }}/{{ repository_name }}'

cvmfs_public_key_path: '/etc/cvmfs/keys/infn.it'

cvmfs_public_key: '{{ repository_name }}.pub'

# Allow to mount cvmfs molumes with preconfigured files from cvmfs-config-default package
cvmfs_preconfigured: false

proxy_url: 'DIRECT'

proxy_port: 80

cvmfs_http_proxy: 'http://{{ proxy_url }}:{{ proxy_port }}'

cvmfs_mountpoint: '/cvmfs'

add_fstab_entry: true

snapshotter: false

snapshotter_path: '/usr/local/share'
